package Frontend.login_signup_page;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * The `LoginController` class handles user actions for login and signup processes.
 * It implements the `ActionListener` interface to respond to button click events
 * and communicate with the `LoginModel`.
 */
public class LoginController implements ActionListener {
    private LoginModel model; // The model that stores the login or signup data

    /**
     * Constructs a `LoginController` with the specified `LoginModel`.
     * This controller is responsible for handling user interactions.
     * 
     * @param m - the model associated with this controller
     */
    public LoginController(LoginModel m) {
        this.model = m;
    }

    /**
     * Handles action events triggered by user interactions, such as login or signup attempts.
     * The event is processed to extract the necessary details for either login or signup.
     * 
     * @param e - the `ActionEvent` generated by user interaction
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        String command = e.getActionCommand();

        String[] commands = command.split(":");

        if (commands.length == 3) {
            String username = commands[1];
            String password = commands[2];

            model.notifyObservers(username + ":" + password);
        }
        else {
            model.notifyObservers(command);
        }
    }

    /**
     * Adds an observer to the `LoginModel` to receive updates about login or signup events.
     * Observers will be notified when a login or signup attempt occurs.
     * 
     * @param observer - the `LoginObserver` to be registered with the model
     */
    public void addObserver(LoginObserver observer) {
        this.model.registerObserver(observer);
    }
}
